# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 18:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import registrations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoBParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$|^$')])),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BoBRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=200)),
                ('facebook_link', models.URLField()),
                ('audio_sample', models.FileField(max_length=255, upload_to=registrations.models.BoBRegistration.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('prelims_venue', models.CharField(choices=[('BLR', 'Bangalore'), ('CCU', 'Kolkata'), ('MAD', 'Chennai'), ('DEL', 'Delhi'), ('BOM', 'Mumbai')], default='BLR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProsceniumStreetPlayParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('accompanist', 'Accompanist'), ('performance', 'Performance')], default='performance', max_length=11)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(max_length=255, upload_to=registrations.models.ProsceniumStreetPlayParticipant.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='ProsceniumStreetPlayRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('contact1', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$|^$')])),
                ('contact2', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$|^$')])),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ka', 'Kannada')], default='en', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProsceniumTheatreParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('accompanist', 'Accompanist'), ('performance', 'Performance')], default='performance', max_length=11)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(max_length=255, upload_to=registrations.models.ProsceniumTheatreParticipant.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='ProsceniumTheatreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('contact1', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$|^$')])),
                ('contact2', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$|^$')])),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ka', 'Kannada')], default='en', max_length=2)),
                ('prelims_video', models.FileField(max_length=255, upload_to=registrations.models.ProsceniumTheatreRegistration.upload_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', '3gp', 'mkv'])])),
                ('prelims_script', models.FileField(max_length=255, upload_to=registrations.models.ProsceniumTheatreRegistration.upload_script_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='prosceniumtheatreregistration',
            unique_together=set([('institution', 'language')]),
        ),
        migrations.AddField(
            model_name='prosceniumtheatreparticipant',
            name='registration_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.ProsceniumTheatreRegistration'),
        ),
        migrations.AlterUniqueTogether(
            name='prosceniumstreetplayregistration',
            unique_together=set([('institution', 'language')]),
        ),
        migrations.AddField(
            model_name='prosceniumstreetplayparticipant',
            name='registration_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.ProsceniumStreetPlayRegistration'),
        ),
        migrations.AlterUniqueTogether(
            name='bobregistration',
            unique_together=set([('band_name', 'city', 'genre')]),
        ),
        migrations.AddField(
            model_name='bobparticipant',
            name='registration_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.BoBRegistration'),
        ),
    ]
