# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import registrations.customfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('accompanist', 'Accompanist'), ('participant', 'Participant')], default='participant', max_length=11)),
                ('age', registrations.customfields.IntegerRangeField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProsceniumRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='participants',
            name='registration_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.ProsceniumRegistration'),
        ),
    ]
