# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobregistration',
            name='prelims_venue',
            field=models.CharField(choices=[('BLR', 'Bangalore'), ('CCU', 'Kolkata'), ('MAD', 'Chennai'), ('DEL', 'Delhi'), ('BOM', 'Mumbai')], default='BLR', max_length=3),
        ),
    ]
