# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosceniumstreetplayparticipant',
            name='role',
            field=models.CharField(choices=[('accompanist', 'Accompanist'), ('performer', 'Performer')], default='performer', max_length=11),
        ),
        migrations.AlterField(
            model_name='prosceniumtheatreparticipant',
            name='role',
            field=models.CharField(choices=[('accompanist', 'Accompanist'), ('performer', 'Performer')], default='performer', max_length=11),
        ),
    ]
