# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20171018_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participants',
            new_name='ProsceniumParticipants',
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='contact1',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$|^$')]),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='contact2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$|^$')]),
        ),
    ]
