# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 19:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20171024_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobparticipant',
            name='contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+?1?\\d{12}$|^$')]),
        ),
        migrations.AlterField(
            model_name='lasyaparticipant',
            name='contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+?1?\\d{12}$|^$')]),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+?1?\\d{12}$|^$')]),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='prosceniumstreetplayregistration',
            name='contact1',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+?1?\\d{12}$|^$')]),
        ),
        migrations.AlterField(
            model_name='prosceniumstreetplayregistration',
            name='contact2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+?1?\\d{12}$|^$')]),
        ),
        migrations.AlterField(
            model_name='prosceniumtheatreregistration',
            name='contact1',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+?1?\\d{12}$|^$')]),
        ),
        migrations.AlterField(
            model_name='prosceniumtheatreregistration',
            name='contact2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+?1?\\d{12}$|^$')]),
        ),
        migrations.AlterUniqueTogether(
            name='lasyaregistration',
            unique_together=set([('name', 'institution')]),
        ),
    ]
