# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20171018_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProsceniumParticipants',
            new_name='ProsceniumParticipant',
        ),
    ]
