# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20171018_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosceniumparticipant',
            name='age',
            field=models.IntegerField(),
        ),
    ]
