# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20171026_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobregistration',
            name='prelims_venue',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Kolkata', 'Kolkata'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai')], default='Bangalore', max_length=9),
        ),
        migrations.AlterField(
            model_name='prosceniumstreetplayparticipant',
            name='role',
            field=models.CharField(choices=[('Accompanist', 'Accompanist'), ('Performer', 'Performer')], default='Performer', max_length=11),
        ),
        migrations.AlterField(
            model_name='prosceniumstreetplayregistration',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada')], default='English', max_length=7),
        ),
        migrations.AlterField(
            model_name='prosceniumtheatreparticipant',
            name='role',
            field=models.CharField(choices=[('Accompanist', 'Accompanist'), ('Performer', 'Performer')], default='Performer', max_length=11),
        ),
        migrations.AlterField(
            model_name='prosceniumtheatreregistration',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada')], default='English', max_length=7),
        ),
        migrations.AlterField(
            model_name='sinecparticipant',
            name='student_type',
            field=models.CharField(choices=[('UG', 'UG'), ('Masters', 'Masters'), ('Ph.D.', 'Ph.D.'), ('Post-Doc', 'Post-Doc')], default='UG', max_length=8),
        ),
        migrations.AlterField(
            model_name='sinecregistration',
            name='privacy_preference',
            field=models.CharField(choices=[('Available for Public Awareness', 'I would like my project to be presented and evaluated in a closed room and would not like to display it to the general public.'), ('Unavailabable for Public Awareness, Closed Room Presentation and Evaluation', 'I would like to display my project to the general public to improve awareness about my project.')], default='Unavailabable for Public Awareness, Closed Room Presentation and Evaluation', max_length=75),
        ),
    ]
