# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20171027_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobregistration',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bobregistration',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
