# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20171028_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobregistration',
            name='audio_sample',
        ),
        migrations.AddField(
            model_name='bobregistration',
            name='audio_sample_file',
            field=models.FileField(blank=True, max_length=255, upload_to=registrations.models.BoBRegistration.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='bobregistration',
            name='audio_sample_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bobparticipant',
            name='contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='lasyaparticipant',
            name='contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='prosceniumstreetplayregistration',
            name='contact1',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='prosceniumstreetplayregistration',
            name='contact2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='prosceniumtheatreregistration',
            name='contact1',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='prosceniumtheatreregistration',
            name='contact2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='sinecregistration',
            name='contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91----------'. 12 digits allowed.", regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')]),
        ),
    ]
